import assert from "node:assert/strict";
import { requireDisposableDatabase } from "./require-disposable-database";
await requireDisposableDatabase();
const { db } = await import("../../src/lib/db");
const { tenants, user, member, socialAccounts, themePages, scouts, customAgents, customAgentAccounts, customAgentVersions, customAgentRuns } = await import("../../src/lib/db/schema");
const { saveAgencyAgent, changeAgencyAgentState, reserveAgencyRun, finishAgencyRun, registerAgencyThread, listAgencyThreads, detachAgencyResource } = await import("../../src/lib/agency/service");
const { default: agencyHook } = await import("../../agent/hooks/agency");
const { authorizeAgencyRoute } = await import("../../agent/lib/agency-route-auth");
const { and, eq, inArray } = await import("drizzle-orm");
const tenantId = crypto.randomUUID(), foreignTenantId = crypto.randomUUID();
const ownerId = crypto.randomUUID(), memberId = crypto.randomUUID();
const owner = { tenantId, userId: ownerId }, drafter = { tenantId, userId: memberId };
try {
  await db.insert(tenants).values([{ id: tenantId, name: "Disposable agency", slug: tenantId }, { id: foreignTenantId, name: "Disposable foreign", slug: foreignTenantId }]);
  await db.insert(user).values([ownerId, memberId].map(id => ({ id, name: "Acceptance", email: `${id}@test.invalid`, emailVerified: false, createdAt: new Date(), updatedAt: new Date() })));
  await db.insert(member).values([{ id: crypto.randomUUID(), organizationId: tenantId, userId: ownerId, role: "owner", createdAt: new Date() }, { id: crypto.randomUUID(), organizationId: tenantId, userId: memberId, role: "member", createdAt: new Date() }]);
  const [account, foreignAccount] = await db.insert(socialAccounts).values([{ tenantId, platform: "instagram", platformAccountId: "disposable" }, { tenantId: foreignTenantId, platform: "instagram", platformAccountId: "foreign" }]).returning();
  const [page] = await db.insert(themePages).values({ tenantId, name: "Acceptance", connectedAccounts: [account.id] }).returning();
  const [scout] = await db.insert(scouts).values({ tenantId, name: "Acceptance", targetUrl: "https://instagram.com/disposable", goalCondition: "new post", isActive: false }).returning();
  const config = { name: "Scout editor", scoutId: scout.id, themePageId: page.id, accountIds: [account.id], dailyDraftLimit: 2 };
  const agent = await saveAgencyAgent(drafter, config);
  assert.equal(agent.state, "paused"); assert.equal(agent.approvedVersion, null);
  await assert.rejects(saveAgencyAgent(owner, { ...config, accountIds: [foreignAccount.id] }), /active destination/);
  await assert.rejects(db.insert(customAgentAccounts).values({ tenantId, agentId: agent.id, accountId: foreignAccount.id }), (error: unknown) => (error as { cause?: { code?: string } }).cause?.code === "23503");
  await assert.rejects(changeAgencyAgentState(drafter, agent.id, 1, "active"), /owners or admins/);
  await changeAgencyAgentState(owner, agent.id, 1, "active");
  await assert.rejects(saveAgencyAgent(drafter, config, { id: agent.id, version: 1 }), /edit an active/);
  const claims = await Promise.allSettled(Array.from({ length: 8 }, (_, i) => reserveAgencyRun(owner, agent.id, 1, `event-${i}`)));
  assert.equal(claims.filter(claim => claim.status === "fulfilled" && claim.value.claimed).length, 2, "eight concurrent events cannot exceed two draft slots");
  const run = claims.find(claim => claim.status === "fulfilled")!;
  if (run.status !== "fulfilled") throw new Error("No run claimed");
  const replay = await reserveAgencyRun(owner, agent.id, 1, run.value.run.eventKey);
  assert.equal(replay.claimed, false); assert.equal(replay.run.id, run.value.run.id);
  await db.update(customAgentRuns).set({ attempt: 3, leaseExpiresAt: new Date(Date.now() - 1000) }).where(eq(customAgentRuns.id, run.value.run.id));
  const exhausted = await reserveAgencyRun(owner, agent.id, 1, run.value.run.eventKey);
  assert.equal(exhausted.claimed, false); assert.equal(exhausted.run.status, "failed");
  await assert.rejects(reserveAgencyRun(owner, agent.id, 1, "quota-still-consumed"), /daily draft limit/);
  const sessionId = `session-${agent.id}`;
  const principal = { authenticator: "better-auth", attributes: { ...owner, customAgentId: agent.id, customAgentVersion: "1" } };
  const onStarted = agencyHook.events?.["session.started"];
  assert(onStarted, "Eve session ownership hook must be installed");
  await onStarted({} as never, { session: { id: sessionId, auth: { initiator: principal, current: principal } } } as never);
  const stream = new Request(`https://joey.test/eve/v1/session/${sessionId}/stream`);
  await assert.rejects(authorizeAgencyRoute(stream, drafter), /Conversation not found/);
  assert.equal((await authorizeAgencyRoute(stream, owner))?.id, agent.id);
  await assert.rejects(registerAgencyThread(drafter, agent.id, 1, `session-${agent.id}`), /Conversation not found/);
  assert.equal((await listAgencyThreads(drafter, agent.id)).length, 0);
  assert.equal((await listAgencyThreads(owner, agent.id)).length, 1);
  const changed = await saveAgencyAgent(owner, { ...config, description: "New instructions" }, { id: agent.id, version: 1 });
  assert.equal(changed.configVersion, 2); assert.equal(changed.state, "paused"); assert.equal(changed.approvedVersion, null);
  assert.equal(await finishAgencyRun(run.value.run, "completed"), false, "old workers cannot complete changed configurations");
  await assert.rejects(reserveAgencyRun(owner, agent.id, 1, "new-event"), /current agent configuration/);
  await assert.rejects(saveAgencyAgent(owner, config, { id: agent.id, version: 1 }), /changed before/);
  assert.equal((await db.query.customAgentVersions.findMany({ where: eq(customAgentVersions.agentId, agent.id) })).length, 2);
  const accountless = await saveAgencyAgent(owner, { name: "Unbound writer" });
  const { default: draftTool } = await import("../../agent/tools/draft_post");
  const unboundPrincipal = { attributes: { ...owner, customAgentId: accountless.id, customAgentVersion: "1" } };
  const unboundResult = await draftTool.execute!({ platform: "instagram", content: "A safe test draft", accountIds: undefined, variants: undefined, mediaUrls: undefined, scheduledFor: undefined }, { session: { auth: { current: unboundPrincipal, initiator: unboundPrincipal } } } as never);
  assert.match(JSON.stringify(unboundResult), /No active bound account/);
  await changeAgencyAgentState(owner, agent.id, 2, "active");
  await assert.rejects(db.transaction(tx => detachAgencyResource(tx, drafter, { kind: "scout", id: scout.id })), /admins can remove/);
  await db.transaction(async tx => { await detachAgencyResource(tx, owner, { kind: "scout", id: scout.id }); await tx.delete(scouts).where(eq(scouts.id, scout.id)); });
  const detached = await db.query.customAgents.findFirst({ where: eq(customAgents.id, agent.id) });
  assert.equal(detached?.scoutId, null); assert.equal(detached?.state, "paused"); assert.equal(detached?.configVersion, 3);
  await changeAgencyAgentState(owner, agent.id, 3, "archived");
  await db.transaction(async tx => { await detachAgencyResource(tx, owner, { kind: "page", id: page.id }); await tx.delete(themePages).where(eq(themePages.id, page.id)); });
  assert.equal((await db.query.customAgents.findFirst({ where: eq(customAgents.id, agent.id) }))?.themePageId, null, "archived agents must not prevent deletion either");
  await db.delete(member).where(and(eq(member.organizationId, tenantId), eq(member.userId, memberId)));
  await assert.rejects(listAgencyThreads(drafter, agent.id), /access denied/);
  assert.equal((await db.query.customAgentRuns.findMany({ where: eq(customAgentRuns.agentId, agent.id) })).length, 2);
  console.log("Agency acceptance passed: paused creation, member/admin boundaries, composite tenant account FK, eight-way quota fencing, event replay, version revocation, private Eve threads, removed memberships. No paid providers called.");
} finally {
  await db.delete(tenants).where(inArray(tenants.id, [tenantId, foreignTenantId]));
  await db.delete(user).where(inArray(user.id, [ownerId, memberId]));
}
process.exit(0);
