import assert from "node:assert/strict";
import { requireDisposableDatabase } from "./require-disposable-database";
await requireDisposableDatabase();
const { db } = await import("../../src/lib/db");
const { tenants, user, member, socialAccounts, themePages, scouts, customAgents, customAgentAccounts, customAgentVersions, customAgentRuns, themeContentFormats, contentPackages, storyClusters, assets, mediaRenderJobs } = await import("../../src/lib/db/schema");
const { saveAgencyAgent, changeAgencyAgentState, reserveAgencyRun, finishAgencyRun, registerAgencyThread, listAgencyThreads, listAgencyRuns, detachAgencyResource, assertAgencyRunCurrent, guardAgencyScoutChange, attachAgencyDraft, recordAgencyDispatchExpiry } = await import("../../src/lib/agency/service");
const { default: agencyHook } = await import("../../agent/hooks/agency");
const { authorizeAgencyRoute } = await import("../../agent/lib/agency-route-auth");
const { and, eq, inArray } = await import("drizzle-orm");
const tenantId = crypto.randomUUID(), foreignTenantId = crypto.randomUUID();
const ownerId = crypto.randomUUID(), memberId = crypto.randomUUID();
const owner = { tenantId, userId: ownerId }, drafter = { tenantId, userId: memberId };
try {
  await db.insert(tenants).values([{ id: tenantId, name: "Disposable agency", slug: tenantId }, { id: foreignTenantId, name: "Disposable foreign", slug: foreignTenantId }]);
  await db.insert(user).values([ownerId, memberId].map(id => ({ id, name: "Acceptance", email: `${id}@test.invalid`, emailVerified: false, createdAt: new Date(), updatedAt: new Date() })));
  await db.insert(member).values([{ id: crypto.randomUUID(), organizationId: tenantId, userId: ownerId, role: "owner", createdAt: new Date() }, { id: crypto.randomUUID(), organizationId: tenantId, userId: memberId, role: "member", createdAt: new Date() }]);
  const [account, foreignAccount] = await db.insert(socialAccounts).values([{ tenantId, platform: "instagram", platformAccountId: "disposable" }, { tenantId: foreignTenantId, platform: "instagram", platformAccountId: "foreign" }]).returning();
  const [page] = await db.insert(themePages).values({ tenantId, name: "Acceptance", connectedAccounts: [account.id] }).returning();
  const [scout] = await db.insert(scouts).values({ tenantId, name: "Acceptance", targetUrl: "https://instagram.com/disposable", goalCondition: "new post", isActive: false }).returning();
  const config = { name: "Scout editor", scoutId: scout.id, themePageId: page.id, accountIds: [account.id], dailyDraftLimit: 2 };
  const [otherPage] = await db.insert(themePages).values({ tenantId, name: "New binding", connectedAccounts: [account.id] }).returning();
  const [format] = await db.insert(themeContentFormats).values({ tenantId, slug: "acceptance", name: "Acceptance", platform: "instagram", mediaType: "image", renderer: "satori" }).returning();
  const [historicalPackage] = await db.insert(contentPackages).values({ tenantId, themePageId: page.id, formatId: format.id, title: "Historical draft" }).returning();
  const historyAgent = await saveAgencyAgent(owner, config);
  await changeAgencyAgentState(owner, historyAgent.id, 1, "active");
  const historicalRun = await reserveAgencyRun(owner, historyAgent.id, 1, "historical");
  assert.equal(await finishAgencyRun(historicalRun.run, "completed", { packageId: historicalPackage.id }), true);
  await saveAgencyAgent(owner, { ...config, themePageId: otherPage.id }, { id: historyAgent.id, version: 1 });
  assert.equal((await listAgencyRuns(owner, historyAgent.id))[0].packageThemePageId, page.id, "History resolves the original package page after rebinding the agent");
  const agent = await saveAgencyAgent(drafter, config);
  assert.equal(agent.state, "paused"); assert.equal(agent.approvedVersion, null);
  await assert.rejects(saveAgencyAgent(owner, { ...config, accountIds: [foreignAccount.id] }), /active destination/);
  await assert.rejects(db.insert(customAgentAccounts).values({ tenantId, agentId: agent.id, accountId: foreignAccount.id }), (error: unknown) => (error as { cause?: { code?: string } }).cause?.code === "23503");
  await assert.rejects(changeAgencyAgentState(drafter, agent.id, 1, "active"), /owners or admins/);
  await changeAgencyAgentState(owner, agent.id, 1, "active");
  assert.equal((await db.query.customAgents.findFirst({ where: eq(customAgents.id, agent.id) }))?.approvedBy, ownerId);
  await assert.rejects(db.transaction(tx => guardAgencyScoutChange(tx, owner, scout.id)), /Pause the bound agent/);
  await assert.rejects(db.transaction(tx => guardAgencyScoutChange(tx, owner, scout.id, true)), /Unbind this Scout/);
  const retryAgent = await saveAgencyAgent(owner, { ...config, name: "Retry acceptance" });
  await changeAgencyAgentState(owner, retryAgent.id, 1, "active");
  const firstAttempt = await reserveAgencyRun(owner, retryAgent.id, 1, "same-source");
  await finishAgencyRun(firstAttempt.run, "failed");
  const secondAttempt = await reserveAgencyRun(owner, retryAgent.id, 1, "same-source");
  assert.equal(secondAttempt.run.attempt, 2);
  await finishAgencyRun(secondAttempt.run, "failed");
  await assert.rejects(reserveAgencyRun(owner, retryAgent.id, 1, "same-source"), /daily draft limit/);
  await saveAgencyAgent(owner, { ...config, name: "Retry acceptance v2" }, { id: retryAgent.id, version: 1 });
  await changeAgencyAgentState(owner, retryAgent.id, 2, "active");
  await assert.rejects(reserveAgencyRun(owner, retryAgent.id, 2, "changed-version"), /daily draft limit/);
  await assert.rejects(saveAgencyAgent(drafter, config, { id: agent.id, version: 1 }), /edit an active/);
  const claims = await Promise.allSettled(Array.from({ length: 8 }, (_, i) => reserveAgencyRun(owner, agent.id, 1, `event-${i}`)));
  assert.equal(claims.filter(claim => claim.status === "fulfilled" && claim.value.claimed).length, 2, "eight concurrent events cannot exceed two draft slots");
  const run = claims.find(claim => claim.status === "fulfilled")!;
  if (run.status !== "fulfilled") throw new Error("No run claimed");
  assert.deepEqual((await assertAgencyRunCurrent(run.value.run)).config.accountIds, [account.id]);
  await db.update(customAgents).set({ approvedBy: memberId }).where(eq(customAgents.id, agent.id));
  await assert.rejects(assertAgencyRunCurrent(run.value.run), /authority was revoked/);
  await assert.rejects(reserveAgencyRun(owner, agent.id, 1, "revoked-approver"), /no longer has workspace authority/);
  await db.update(customAgents).set({ approvedBy: ownerId }).where(eq(customAgents.id, agent.id));
  const replay = await reserveAgencyRun(owner, agent.id, 1, run.value.run.eventKey);
  assert.equal(replay.claimed, false); assert.equal(replay.run.id, run.value.run.id);
  await db.update(customAgentRuns).set({ attempt: 3, leaseExpiresAt: new Date(Date.now() - 1000) }).where(eq(customAgentRuns.id, run.value.run.id));
  const exhausted = await reserveAgencyRun(owner, agent.id, 1, run.value.run.eventKey);
  assert.equal(exhausted.claimed, false); assert.equal(exhausted.run.status, "failed");
  await assert.rejects(reserveAgencyRun(owner, agent.id, 1, "quota-still-consumed"), /daily draft limit/);
  const sessionId = `session-${agent.id}`;
  const principal = { authenticator: "better-auth", attributes: { ...owner, customAgentId: agent.id, customAgentVersion: "1" } };
  const onStarted = agencyHook.events?.["session.started"];
  assert(onStarted, "Eve session ownership hook must be installed");
  await onStarted({} as never, { session: { id: sessionId, auth: { initiator: principal, current: principal } } } as never);
  const stream = new Request(`https://joey.test/eve/v1/session/${sessionId}/stream`);
  await assert.rejects(authorizeAgencyRoute(stream, drafter), /Conversation not found/);
  assert.equal((await authorizeAgencyRoute(stream, owner))?.id, agent.id);
  await assert.rejects(registerAgencyThread(drafter, agent.id, 1, `session-${agent.id}`), /Conversation not found/);
  assert.equal((await listAgencyThreads(drafter, agent.id)).length, 0);
  assert.equal((await listAgencyThreads(owner, agent.id)).length, 1);
  const changed = await saveAgencyAgent(owner, { ...config, description: "New instructions" }, { id: agent.id, version: 1 });
  assert.equal(changed.configVersion, 2); assert.equal(changed.state, "paused"); assert.equal(changed.approvedVersion, null);
  assert.equal(await finishAgencyRun(run.value.run, "completed"), false, "old workers cannot complete changed configurations");
  await assert.rejects(reserveAgencyRun(owner, agent.id, 1, "new-event"), /current agent configuration/);
  await assert.rejects(saveAgencyAgent(owner, config, { id: agent.id, version: 1 }), /changed before/);
  assert.equal((await db.query.customAgentVersions.findMany({ where: eq(customAgentVersions.agentId, agent.id) })).length, 2);
  // Use the actual PostgreSQL commit/attachment path; fake only completed
  // provider output, never the permission, lease or package fences.
  const workerAgent = await saveAgencyAgent(owner, { ...config, name: "Async acceptance", dailyDraftLimit: 12 });
  await changeAgencyAgentState(owner, workerAgent.id, 1, "active");
  await assert.rejects(recordAgencyDispatchExpiry(drafter, workerAgent.id, 1, "2000-01-01"), /admins/);
  const expiryReceipt = await recordAgencyDispatchExpiry(owner, workerAgent.id, 1, "2000-01-01");
  assert.equal(expiryReceipt.duplicate, false);
  assert.deepEqual(await recordAgencyDispatchExpiry(owner, workerAgent.id, 1, "2000-01-01"), { ...expiryReceipt, duplicate: true }, "expired dispatches deduplicate without replacing history");
  const expiry = await db.query.customAgentRuns.findFirst({ where: eq(customAgentRuns.id, expiryReceipt.id) });
  assert.equal(expiry?.status, "cancelled"); assert.equal(expiry?.attempt, 0, "an expired dispatch does not consume quota");
  const priorDayRun = await reserveAgencyRun(owner, workerAgent.id, 1, "daily:2000-01-02");
  assert.equal(await finishAgencyRun(priorDayRun.run, "completed", { packageId: historicalPackage.id }), true);
  assert.deepEqual(await recordAgencyDispatchExpiry(owner, workerAgent.id, 1, "2000-01-02"), { id: priorDayRun.run.id, status: "completed", packageId: historicalPackage.id, duplicate: true }, "a delayed child preserves the completed manual outcome and draft link");
  assert.equal((await db.query.customAgentRuns.findFirst({ where: eq(customAgentRuns.id, priorDayRun.run.id) }))?.attempt, 1, "expiry replay cannot replace a paid receipt");
  const expiryOnly = await saveAgencyAgent(owner, { ...config, name: "Zero-credit expiry", dailyDraftLimit: 1 });
  await changeAgencyAgentState(owner, expiryOnly.id, 1, "active");
  await recordAgencyDispatchExpiry(owner, expiryOnly.id, 1, "2000-01-01");
  assert.equal((await reserveAgencyRun(owner, expiryOnly.id, 1, "current-day-check")).claimed, true, "zero-attempt history leaves the single paid slot available");
  await assert.rejects(reserveAgencyRun(owner, expiryOnly.id, 1, "second-paid-check"), /daily draft limit/);
  const workerRun = await reserveAgencyRun(owner, workerAgent.id, 1, "queued-video");
  const { claimScoutRemix, saveScoutRemixDraft } = await import("../../src/lib/scouts/remix-receipts");
  const sourceClaim = await claimScoutRemix({ tenantId, scoutId: scout.id, themePageId: page.id, eventKey: "agency-queued-video" });
  const [videoFormat] = await db.insert(themeContentFormats).values({ tenantId, slug: "acceptance-video", name: "Video acceptance", platform: "instagram", mediaType: "video", renderer: "ffmpeg" }).returning();
  const saved = await saveScoutRemixDraft(sourceClaim.receipt,
    { tenantId, themePageId: page.id, title: "Video evidence", facts: [], memberItemIds: [] },
    { tenantId, themePageId: page.id, formatId: videoFormat.id, title: "Original video", status: "pending_review" },
    tx => assertAgencyRunCurrent(workerRun.run, tx).then(() => undefined),
    (tx, packageId) => attachAgencyDraft(tx, workerRun.run, packageId));
  assert.equal((await db.query.customAgentRuns.findFirst({ where: eq(customAgentRuns.id, workerRun.run.id) }))?.packageId, saved.pkg.id, "the run receives its draft in the same atomic commit");
  assert.equal(await finishAgencyRun(workerRun.run, "queued", { packageId: saved.pkg.id }), true);
  const { themeRenderInput, settleThemeRender } = await import("../../src/lib/media-engine/theme-adapter");
  const { revision } = await themeRenderInput(tenantId, saved.pkg.id);
  const [output] = await db.insert(assets).values({ tenantId, filename: "acceptance.mp4", key: `${tenantId}/acceptance.mp4`, mimeType: "video/mp4", size: 100, publicUrl: "https://assets.example.test/acceptance.mp4" }).returning();
  const [job] = await db.insert(mediaRenderJobs).values({ tenantId, inputHash: crypto.randomUUID(), spec: { source: { kind: "theme_package", id: saved.pkg.id, revision } }, status: "succeeded", outputAssetId: output.id }).returning();
  await db.update(contentPackages).set({ metrics: { renderJobId: job.id, renderRevision: revision }, caption: "Caption edits keep pixels." }).where(eq(contentPackages.id, saved.pkg.id));
  await settleThemeRender(tenantId, saved.pkg.id);
  assert.equal((await db.query.customAgentRuns.findFirst({ where: eq(customAgentRuns.id, workerRun.run.id) }))?.status, "completed", "a real fenced MP4 attachment settles queued history");
  const videoPackage = await db.query.contentPackages.findFirst({ where: eq(contentPackages.id, saved.pkg.id) });
  assert.equal((videoPackage?.renderedAssetUrls as Array<{ type: string }>)[0]?.type, "video");
  assert.equal(await finishAgencyRun(workerRun.run, "queued", { packageId: saved.pkg.id }), false, "a late dispatcher cannot revert terminal worker completion");
  const blockedRun = await reserveAgencyRun(owner, workerAgent.id, 1, "pause-before-commit");
  const blockedSource = await claimScoutRemix({ tenantId, scoutId: scout.id, themePageId: page.id, eventKey: "agency-paused-source" });
  await changeAgencyAgentState(owner, workerAgent.id, 1, "paused");
  await assert.rejects(saveScoutRemixDraft(blockedSource.receipt,
    { tenantId, themePageId: page.id, title: "Must not commit", facts: [], memberItemIds: [] },
    { tenantId, themePageId: page.id, formatId: videoFormat.id, title: "Must not commit", status: "pending_review" },
    tx => assertAgencyRunCurrent(blockedRun.run, tx).then(() => undefined),
    (tx, packageId) => attachAgencyDraft(tx, blockedRun.run, packageId)), /paused/);
  assert.equal((await db.query.storyClusters.findMany({ where: and(eq(storyClusters.tenantId, tenantId), eq(storyClusters.title, "Must not commit")) })).length, 0, "pausing before atomic commit creates neither a cluster nor a draft");
  const blocked = await db.query.customAgentRuns.findFirst({ where: eq(customAgentRuns.id, blockedRun.run.id) });
  assert.equal(blocked?.status, "cancelled"); assert.equal(blocked?.packageId, null);
  const accountless = await saveAgencyAgent(owner, { name: "Unbound writer" });
  const { default: draftTool } = await import("../../agent/tools/draft_post");
  const unboundPrincipal = { principalType: "user", principalId: JSON.stringify([owner.userId, owner.tenantId]), attributes: { ...owner, customAgentId: accountless.id, customAgentVersion: "1" } };
  const unboundResult = await draftTool.execute!({ platform: "instagram", content: "A safe test draft", accountIds: undefined, variants: undefined, mediaUrls: undefined, scheduledFor: undefined }, { session: { auth: { current: unboundPrincipal, initiator: unboundPrincipal } } } as never);
  assert.match(JSON.stringify(unboundResult), /No active bound account/);
  await changeAgencyAgentState(owner, agent.id, 2, "active");
  await assert.rejects(db.transaction(tx => detachAgencyResource(tx, drafter, { kind: "scout", id: scout.id })), /admins can remove/);
  await db.transaction(async tx => { await detachAgencyResource(tx, owner, { kind: "scout", id: scout.id }); await tx.delete(scouts).where(eq(scouts.id, scout.id)); });
  const detached = await db.query.customAgents.findFirst({ where: eq(customAgents.id, agent.id) });
  assert.equal(detached?.scoutId, null); assert.equal(detached?.state, "paused"); assert.equal(detached?.configVersion, 3);
  await changeAgencyAgentState(owner, agent.id, 3, "archived");
  await db.transaction(async tx => { await detachAgencyResource(tx, owner, { kind: "page", id: page.id }); await tx.delete(themePages).where(eq(themePages.id, page.id)); });
  assert.equal((await db.query.customAgents.findFirst({ where: eq(customAgents.id, agent.id) }))?.themePageId, null, "archived agents must not prevent deletion either");
  await db.delete(member).where(and(eq(member.organizationId, tenantId), eq(member.userId, memberId)));
  await assert.rejects(listAgencyThreads(drafter, agent.id), /access denied/);
  assert.equal((await db.query.customAgentRuns.findMany({ where: eq(customAgentRuns.agentId, agent.id) })).length, 2);
  console.log("Agency acceptance passed: paused creation, member/admin boundaries, composite tenant account FK, eight-way quota fencing, event replay, version revocation, private Eve threads, removed memberships. No paid providers called.");
} finally {
  await db.delete(tenants).where(inArray(tenants.id, [tenantId, foreignTenantId]));
  await db.delete(user).where(inArray(user.id, [ownerId, memberId]));
}
process.exit(0);
