import assert from "node:assert/strict";
import { requireDisposableDatabase } from "./require-disposable-database";
await requireDisposableDatabase();
process.env.MEDIA_ENGINE_ENABLED = "true";
process.env.R2_PUBLIC_URL = "https://assets.example.test";
const { db } = await import("../../src/lib/db");
const { tenants, assets, flows, mediaRenderJobs, mediaTranscripts, contentPackages, themePages, themeContentFormats, apiKeys, usageTracking } = await import("../../src/lib/db/schema");
const { submitRender, getRender, cancelRender, retryRender } = await import("../../src/lib/media-engine/engine");
const { claimNextRender, completeRenderJob } = await import("../../src/lib/media-engine/worker-jobs");
const { eq, and } = await import("drizzle-orm");
const tenantId = crypto.randomUUID();
let failed = false;
try {
  await db.insert(tenants).values({ id: tenantId, name: "Render integration", slug: tenantId, createdAt: new Date() });
  const [flow] = await db.insert(flows).values({ tenantId, name: "Render flow", graph: {} }).returning();
  const [asset] = await db.insert(assets).values({ tenantId, filename: "test.png", key: `${tenantId}/source.png`, mimeType: "image/png", size: 100, publicUrl: "https://example.test/source.png" }).returning();
  const spec = { version: 1, source: { kind: "flow", id: flow.id, revision: "1" }, template: "photo_headline", templateVersion: 1, format: "png", media: { id: asset.id, version: asset.key }, title: "Test render", brand: { name: "Science", handle: "@science" } };
  const pair = await Promise.all([submitRender(tenantId, spec), submitRender(tenantId, spec)]);
  assert.equal(pair[0].jobId, pair[1].jobId, "identical submissions must create one job");
  await assert.rejects(submitRender("other-tenant", spec), /workspace/);
  await assert.rejects(getRender("other-tenant", pair[0].jobId), /not found/);
  const claims = await Promise.all([claimNextRender(), claimNextRender()]);
  assert.equal(claims.filter(Boolean).length, 1, "only one worker may claim a job");
  const claim = claims.find(Boolean)!;
  await cancelRender(tenantId, claim.id);
  const late = await completeRenderJob({ jobId: claim.id, attemptToken: claim.attemptToken!, success: true, usage: { elapsedSeconds: 1, encoder: "png", outputSeconds: 0 } }, async () => { throw new Error("Cancelled completion must not inspect storage"); });
  assert.equal(late.accepted, false);
  const second = await submitRender(tenantId, { ...spec, source: { ...spec.source, revision: "2" } });
  const old = await claimNextRender();
  assert.equal(old?.id, second.jobId);
  await db.update(mediaRenderJobs).set({ updatedAt: new Date(Date.now() - 700_000) }).where(eq(mediaRenderJobs.id, second.jobId));
  const retry = await claimNextRender();
  assert.equal(retry?.attempt, 2);
  assert.notEqual(retry?.attemptToken, old?.attemptToken);
  const completed = await completeRenderJob({ jobId: retry!.id, attemptToken: retry!.attemptToken!, success: true, usage: { elapsedSeconds: 1, encoder: "png", outputSeconds: 0 } }, async () => ({ ContentLength: 100, ContentType: "image/png", $metadata: {} }));
  assert.equal(completed.accepted, true);
  assert.equal((await getRender(tenantId, retry!.id)).output?.mimeType, "image/png");
  assert.equal((await completeRenderJob({ jobId: old!.id, attemptToken: old!.attemptToken!, success: false, usage: { elapsedSeconds: 1, encoder: "png", outputSeconds: 0 } })).accepted, false);
  const { transcriptHash, transcribeRender } = await import("../../src/lib/media-engine/transcription");
  const [video] = await db.insert(assets).values({ tenantId, filename: "clip.mp4", key: `${tenantId}/clip.mp4`, mimeType: "video/mp4", size: 100, publicUrl: "https://example.test/clip.mp4" }).returning();
  const media = { id: video.id, version: video.key };
  const videoSpec = { ...spec, media, template: "branded_clip", format: "mp4", video: { duration: 15, captions: true } };
  const videoJob = await submitRender(tenantId, videoSpec);
  const videoClaim = await claimNextRender();
  assert.equal(videoClaim?.id, videoJob.jobId);
  const words = [{ text: "Hello", start: .2, end: .7 }];
  await db.insert(mediaTranscripts).values({ tenantId, inputHash: transcriptHash(media, 0, 15), status: "succeeded", attemptToken: "previous-render", words, durationSeconds: 15 });
  assert.deepEqual((await transcribeRender(videoJob.jobId, videoClaim!.attemptToken!)).words, words, "cached transcripts must not need a provider key or network call");
  await cancelRender(tenantId, videoJob.jobId);
  await assert.rejects(transcribeRender(videoJob.jobId, videoClaim!.attemptToken!), /lease/);
  const headlineEdit = await submitRender(tenantId, { ...videoSpec, title: "A changed headline" });
  const headlineClaim = await claimNextRender();
  assert.equal(headlineClaim?.id, headlineEdit.jobId);
  assert.deepEqual((await transcribeRender(headlineEdit.jobId, headlineClaim!.attemptToken!)).words, words, "headline edits must reuse actual transcript timing");
  assert.notEqual(transcriptHash(media, 0, 15), transcriptHash(media, 1, 15), "trimming must invalidate transcription timing");
  await cancelRender(tenantId, headlineEdit.jobId);
  const retried = await retryRender(tenantId, claim.id);
  assert.equal(retried.status, "queued");
  const freshAttempt = await claimNextRender();
  assert.equal(freshAttempt?.id, claim.id);
  assert.notEqual(freshAttempt?.attemptToken, claim.attemptToken);
  assert.equal((await completeRenderJob({ jobId: claim.id, attemptToken: claim.attemptToken!, success: false, usage: { elapsedSeconds: 1, encoder: "png", outputSeconds: 0 } })).accepted, false, "callbacks from a cancelled attempt cannot affect a retried job");
  await cancelRender(tenantId, claim.id);
  await db.update(mediaRenderJobs).set({ attempt: 3 }).where(eq(mediaRenderJobs.id, claim.id));
  await assert.rejects(retryRender(tenantId, claim.id), /three worker attempts/);
  const { invalidateThemeMedia } = await import("../../src/lib/media-engine/invalidation");
  const [page] = await db.insert(themePages).values({ tenantId, name: "News" }).returning();
  const [format] = await db.insert(themeContentFormats).values({ tenantId, slug: "test-image", name: "Image", platform: "instagram", mediaType: "image", renderer: "puppeteer" }).returning();
  const attached = [{ url: "https://example.test/export.png", type: "image" }];
  const [pkg, accepted] = await db.insert(contentPackages).values([
    { tenantId, themePageId: page.id, formatId: format.id, title: "Review me", status: "approved", renderedAssetUrls: attached, updatedAt: new Date(Date.now() - 1000) },
    { tenantId, themePageId: page.id, formatId: format.id, title: "Already submitted", status: "publishing", renderedAssetUrls: attached, metrics: { publishAttemptAt: new Date().toISOString() } },
  ]).returning();
  let editing!: () => void, release!: () => void;
  const entered = new Promise<void>(resolve => { editing = resolve; });
  const hold = new Promise<void>(resolve => { release = resolve; });
  const mutation = db.transaction(async tx => {
    await tx.update(themePages).set({ name: "Updated brand" }).where(eq(themePages.id, page.id));
    await invalidateThemeMedia(tx, tenantId, { kind: "page", id: page.id }, true);
    editing();
    await hold;
  });
  await entered;
  const publication = db.update(contentPackages).set({ status: "publishing" }).where(and(eq(contentPackages.id, pkg.id), eq(contentPackages.status, "approved"), eq(contentPackages.updatedAt, pkg.updatedAt))).returning();
  const pendingClaim = Promise.resolve(publication);
  release();
  await mutation;
  assert.equal((await pendingClaim).length, 0, "an edit that wins must fence an in-flight publication claim");
  const edited = await db.query.contentPackages.findFirst({ where: eq(contentPackages.id, pkg.id) });
  assert.equal(edited?.status, "pending_review");
  assert.deepEqual(edited?.renderedAssetUrls, []);
  const preserved = await db.query.contentPackages.findFirst({ where: eq(contentPackages.id, accepted.id) });
  assert.equal(preserved?.status, "publishing");
  assert.deepEqual(preserved?.renderedAssetUrls, attached, "previously accepted attempts keep their media snapshot");
  await db.update(contentPackages).set({ status: "approved", renderedAssetUrls: attached }).where(eq(contentPackages.id, pkg.id));
  await db.transaction(tx => invalidateThemeMedia(tx, tenantId, { kind: "page", id: page.id }, false));
  assert.deepEqual((await db.query.contentPackages.findFirst({ where: eq(contentPackages.id, pkg.id) }))?.renderedAssetUrls, attached, "non-pixel edits retain rendered media");
  console.log("PASS: transactional edit invalidation, publication fencing and accepted-attempt preservation");
  const { encrypt } = await import("../../src/lib/crypto");
  await db.insert(apiKeys).values({ tenantId, provider: "openai", encryptedKey: encrypt("test-only-key", tenantId), status: "active" });
  process.env.MEDIA_TRANSCRIPTION_USD_PER_MINUTE = "0.006";
  const paidJob = await submitRender(tenantId, { ...videoSpec, video: { duration: 14, captions: true } });
  const paidClaim = await claimNextRender();
  assert.equal(paidClaim?.id, paidJob.jobId);
  let requests = 0;
  const provider = {
    readAudio: async () => Buffer.from("synthetic audio"),
    transcribe: async (key: string) => { assert.equal(key, "test-only-key"); requests++; return { duration: 14, text: "Hello", words: [{ word: "Hello", start: .2, end: .7 }] }; },
  };
  const transcribed = await transcribeRender(paidJob.jobId, paidClaim!.attemptToken!, provider);
  assert.deepEqual(transcribed.words, words);
  await transcribeRender(paidJob.jobId, paidClaim!.attemptToken!, provider);
  assert.equal(requests, 1, "cached success must not repeat a paid provider call");
  const reserved = await db.query.usageTracking.findFirst({ where: eq(usageTracking.tenantId, tenantId) });
  assert.ok(Number(reserved?.estimatedCostUsd) >= .0014, "provider estimate must be reserved before transcription");
  await cancelRender(tenantId, paidJob.jobId);
  const failedJob = await submitRender(tenantId, { ...videoSpec, video: { duration: 13, captions: true } });
  const failedClaim = await claimNextRender();
  assert.equal(failedClaim?.id, failedJob.jobId);
  let failures = 0;
  const failing = { readAudio: provider.readAudio, transcribe: async () => { failures++; throw new Error("ambiguous provider timeout"); } };
  await assert.rejects(transcribeRender(failedJob.jobId, failedClaim!.attemptToken!, failing), /Transcription failed/);
  await assert.rejects(transcribeRender(failedJob.jobId, failedClaim!.attemptToken!, failing), /Transcription failed/);
  assert.equal(failures, 1, "ambiguous provider failures must not silently spend twice");
  console.log("PASS: mocked provider timing, reserved costs, cached success and no duplicate paid failure");
  console.log("PASS: explicit retry fencing and maximum attempts");
  console.log("PASS: transcript cache reuse across layout edits, trim identity and cancelled-job access");
  console.log("PASS: render deduplication, tenant isolation, concurrent claims, cancellation, expired leases, stale completions and immutable output registration");
} catch (error) { console.error(error); failed = true; }
finally { await db.delete(tenants).where(eq(tenants.id, tenantId)); }
process.exit(failed ? 1 : 0);
